apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
spec:
  type: ClusterIP
  ports:
    - port: 9086
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf_img
          imagePullPolicy: Never
          name: telegraf
          ports:
            - containerPort: 9086
          volumeMounts:
            - name: dockersocket
              mountPath: /var/run/docker.sock
      volumes:
         - name: dockersocket
           hostPath:
             path: /var/run/docker.sock
#            type: FileOrCreate