apiVersion: v1
kind: Service
metadata:
  name: nginx-svc2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 81
    - port: 443
      name: https
      protocol: TCP
      targetPort: 444
  selector:
    app: nginx-lbl2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lbl2
  template:
    metadata:
      labels:
        app: nginx-lbl2
    spec:
      containers:
        - image: nginx_img2
          imagePullPolicy: Never
          name: nginx2
          ports:
            - containerPort: 80
            - containerPort: 443
