apiVersion: v1
kind: Service
metadata:
  name: influx-svc
  labels:
    app: influx
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: influx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pv-claim
  labels:
    app: influx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      restartPolicy: Always
      containers:
        - name: influx
          image: influxdb_img
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: influx
          volumeMounts:
            - name: influx-pv-storage
              mountPath: "/var/lib/influxdb"
            - name: dockersocket
              mountPath: /var/run/docker.sock
      volumes:
        - name: influx-pv-storage
          persistentVolumeClaim:
            claimName: influx-pv-claim
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock