apiVersion: v1
kind: Service
metadata:
  name: influx-svc
  labels:
    app: influx
spec:
  type: ClusterIP
  ports:
    - port: 8086
  selector:
    app: influx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deploy
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      restartPolicy: Always
      containers:
        - name: influx
          image: influxdb_img
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              name: influx
          volumeMounts:
            - name: influx-pv-storage
              mountPath: "/var/lib/influxdb"
            - name: dockersocket
              mountPath: /var/run/docker.sock
      volumes:
        - name: influx-pv-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock