apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lbl
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-lbl
    spec:
      containers:
        - image: nginx_img
          imagePullPolicy: Never
          name: nginx
          ports:
            - containerPort: 80
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#  labels:
#    app: nginx-lbl
#spec:
#  containers:
#  - name: nginx
#    image: nginx_img
#    imagePullPolicy: Never
#    ports:
#    - containerPort: 80