apiVersion: v1
kind: Service
metadata:
  name: 1_wordpress-svc
  labels:
    app: 1_wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      protocol: TCP
  selector:
    app: 1_wordpress
#    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: 1_wordpress
spec:
  #storageClassName: manual # from notion...
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1_wordpress
  labels:
    app: 1_wordpress
spec:
  selector:
    matchLabels:
      app: 1_wordpress
#      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: 1_wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress_img
          imagePullPolicy: Never
          name: 1_wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: 1_wordpress-4_mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 4_mysql-pass
                  key: password
          ports:
            - containerPort: 5050
              name: 1_wordpress
          volumeMounts:
            - name: 1_wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: 1_wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
