apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: php-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-lbl
  template:
    metadata:
      labels:
        app: php-lbl
    spec:
      containers:
        - image: php_img
          imagePullPolicy: Never
          name: phpmyadmin
          env:
            - name: WORDPRESS_DB_HOST
              value: 'sql-svc'
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 5000
